Triggered by the following variable: https://www.football-data.co.uk/mmz4281/2021/ D2.csvTraceback (most recent call last):
  File "C:/Dev/udacity_capstone/staging_data/main.py", line 110, in process_current_season
    fd = urlopen(url_path + year_url + '/' + f.replace("'", ""))
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1251, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1094, in putrequest
    self._validate_path(url)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1185, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/mmz4281/2021/ D2.csv' (found at least ' ')
Triggered by the following variable: https://www.football-data.co.uk/mmz4281/2021/ F1.csvTraceback (most recent call last):
  File "C:/Dev/udacity_capstone/staging_data/main.py", line 110, in process_current_season
    fd = urlopen(url_path + year_url + '/' + f.replace("'", ""))
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\martyn_woodison\anaconda3\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1251, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1094, in putrequest
    self._validate_path(url)
  File "C:\Users\martyn_woodison\anaconda3\lib\http\client.py", line 1185, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/mmz4281/2021/ F1.csv' (found at least ' ')
